### PR TITLE
Hill Cipher

### PR DESCRIPTION
**Pull request by payallenka**
I have added the Hill Cipher folder which includes the encryption and decryption method. 
The way it can be used is mentioned in the Readme file created within it by me.

### CODE REVIEW

**Comment by payallenka** [comment]
kindly add the hactoberfest-aacecpted tag here.
Thank you for your time.

image

**Comment by intrepidbird** [comment]
cool

**Comment by payallenka** [comment]
It still doesn't solves the problem.
Screenshot (117)

Do you know what can be a potential solution.

**Comment by payallenka** [comment]
Issue resolved - thank you so much for your time :)
Have a great day ahead.

**Pull request merged**
